#!/usr/bin/env bash
#
# install.sh
#
# Interactive installer for pve-node-backup / pve-node-restore.
#
# Run this from within a clone of the repo (it expects pve-node-backup.sh,
# pve-node-restore.sh, and examples/ to be alongside it). It will:
#   - install the two scripts to /usr/local/bin
#   - create a root-only env file with your PBS credentials
#   - install + enable a systemd service/timer (or a cron job, your choice)
#
# Safe to re-run: it will show you current values as defaults and ask
# before overwriting anything.
#
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
BIN_DIR="/usr/local/bin"
ENV_FILE="/etc/pve-node-backup.env"
LIVE_BACKUP_LOG_DIR="/var/log"

BOLD="$(tput bold 2>/dev/null || true)"
RESET="$(tput sgr0 2>/dev/null || true)"

say()  { echo "${BOLD}==>${RESET} $*"; }
warn() { echo "${BOLD}WARNING:${RESET} $*" >&2; }
die()  { echo "${BOLD}ERROR:${RESET} $*" >&2; exit 1; }

require_root() {
    [[ "$(id -u)" -eq 0 ]] || die "Please run this installer as root (sudo ./install.sh)."
}

ask() {
    # ask "prompt" "default" -> echoes chosen value
    local prompt="$1" default="${2:-}" reply
    if [[ -n "$default" ]]; then
        read -r -p "$prompt [$default]: " reply
        echo "${reply:-$default}"
    else
        read -r -p "$prompt: " reply
        echo "$reply"
    fi
}

ask_secret() {
    local prompt="$1" reply
    read -r -s -p "$prompt: " reply
    echo >&2
    echo "$reply"
}

confirm() {
    local prompt="$1" reply
    read -r -p "$prompt [y/N]: " reply
    [[ "$reply" =~ ^[Yy]$ ]]
}

check_source_files() {
    for f in pve-node-backup.sh pve-node-restore.sh \
             examples/pve-node-backup.env.example \
             examples/pve-node-backup.service \
             examples/pve-node-backup.timer; do
        [[ -f "${SCRIPT_DIR}/${f}" ]] || die "Expected file not found: ${SCRIPT_DIR}/${f} (run this from inside the cloned repo)"
    done
}

check_pbc_installed() {
    if command -v proxmox-backup-client >/dev/null 2>&1; then
        say "proxmox-backup-client is already installed."
        return
    fi
    warn "proxmox-backup-client not found."
    if confirm "Install it now via apt?"; then
        apt update && apt install -y proxmox-backup-client
    else
        die "proxmox-backup-client is required. Install it and re-run this installer."
    fi
}

install_scripts() {
    say "Installing scripts to ${BIN_DIR}"
    install -m 750 -o root -g root "${SCRIPT_DIR}/pve-node-backup.sh"  "${BIN_DIR}/pve-node-backup.sh"
    install -m 750 -o root -g root "${SCRIPT_DIR}/pve-node-restore.sh" "${BIN_DIR}/pve-node-restore.sh"
}

collect_credentials() {
    echo
    say "PBS connection details"
    echo "Example repository formats:"
    echo "  user@pbs!tokenname@pbs.example.com:datastore-name   (API token, recommended)"
    echo "  backup@pbs@pbs.example.com:datastore-name           (plain user)"
    echo

    local default_repo=""
    if [[ -f "$ENV_FILE" ]]; then
        default_repo="$(grep -E '^PBS_REPOSITORY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)"
    fi

    PBS_REPOSITORY_VAL="$(ask "PBS repository string" "$default_repo")"
    [[ -n "$PBS_REPOSITORY_VAL" ]] || die "A PBS repository string is required."

    PBS_PASSWORD_VAL="$(ask_secret "PBS password or API token secret (input hidden)")"
    [[ -n "$PBS_PASSWORD_VAL" ]] || die "A password/token secret is required."

    PBS_FINGERPRINT_VAL="$(ask "PBS server TLS fingerprint (leave blank if using a trusted CA cert)" "")"

    NAMESPACE_VAL="$(ask "PBS namespace (leave blank for root namespace)" "")"
}

write_env_file() {
    say "Writing ${ENV_FILE} (mode 600, root-only)"
    umask 077
    {
        echo "# Generated by install.sh on $(date)"
        echo "PBS_REPOSITORY=${PBS_REPOSITORY_VAL}"
        echo "PBS_PASSWORD=${PBS_PASSWORD_VAL}"
        [[ -n "$PBS_FINGERPRINT_VAL" ]] && echo "PBS_FINGERPRINT=${PBS_FINGERPRINT_VAL}"
        [[ -n "$NAMESPACE_VAL" ]] && echo "NAMESPACE=${NAMESPACE_VAL}"
    } > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    chown root:root "$ENV_FILE"
}

test_connection() {
    if confirm "Test the PBS connection now?"; then
        say "Running: proxmox-backup-client list --repository <repo>"
        set +e
        # shellcheck disable=SC1090
        ( set -a; source "$ENV_FILE"; set +a
          proxmox-backup-client list --repository "$PBS_REPOSITORY" )
        local rc=$?
        set -e
        if [[ $rc -eq 0 ]]; then
            say "Connection OK."
        else
            warn "Connection test failed (exit $rc). Check credentials/network and re-run install.sh if needed."
        fi
    fi
}

setup_systemd() {
    say "Installing systemd service + timer"
    sed "s#EnvironmentFile=.*#EnvironmentFile=${ENV_FILE}#; s#ExecStart=.*#ExecStart=${BIN_DIR}/pve-node-backup.sh#" \
        "${SCRIPT_DIR}/examples/pve-node-backup.service" > /etc/systemd/system/pve-node-backup.service

    local schedule
    schedule="$(ask "Daily backup time (HH:MM, 24h)" "03:00")"
    local jitter
    jitter="$(ask "Random jitter in seconds (spreads load if multiple nodes share this schedule)" "600")"

    sed "s#^OnCalendar=.*#OnCalendar=*-*-* ${schedule}:00#; s#^RandomizedDelaySec=.*#RandomizedDelaySec=${jitter}#" \
        "${SCRIPT_DIR}/examples/pve-node-backup.timer" > /etc/systemd/system/pve-node-backup.timer

    systemctl daemon-reload
    systemctl enable --now pve-node-backup.timer
    say "Timer installed and enabled. Check with: systemctl list-timers pve-node-backup.timer"
}

setup_cron() {
    say "Installing cron job"
    local schedule hh mm
    schedule="$(ask "Daily backup time (HH:MM, 24h)" "03:00")"
    hh="${schedule%%:*}"; mm="${schedule##*:}"
    cat > /etc/cron.d/pve-node-backup <<EOF
${mm} ${hh} * * * root . ${ENV_FILE} && ${BIN_DIR}/pve-node-backup.sh >> ${LIVE_BACKUP_LOG_DIR}/pve-node-backup-cron.log 2>&1
EOF
    chmod 644 /etc/cron.d/pve-node-backup
    say "Cron job installed at /etc/cron.d/pve-node-backup"
}

run_backup_now() {
    if confirm "Run a backup right now to verify everything works end-to-end?"; then
        ( set -a; source "$ENV_FILE"; set +a; "${BIN_DIR}/pve-node-backup.sh" )
    fi
}

main() {
    require_root
    check_source_files

    say "pve-node-backup installer"
    echo "This node's hostname (used as the PBS backup-id): $(hostname -s)"
    echo

    check_pbc_installed
    install_scripts
    collect_credentials
    write_env_file
    test_connection

    echo
    say "Scheduling"
    if confirm "Use systemd timer for scheduling? (recommended; choose 'n' for cron instead)"; then
        setup_systemd
    else
        setup_cron
    fi

    echo
    run_backup_now

    echo
    say "Done."
    echo "Backup script:   ${BIN_DIR}/pve-node-backup.sh"
    echo "Restore script:  ${BIN_DIR}/pve-node-restore.sh"
    echo "Credentials:     ${ENV_FILE} (mode 600)"
    echo
    echo "To back up other cluster nodes, copy this repo to each one and re-run"
    echo "install.sh there — each node uses its own hostname as the backup-id,"
    echo "so the same PBS repository/credentials can be reused everywhere."
}

main "$@"
